# Generated by Django 4.2.1 on 2023-05-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_pictures_url_location_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="weather",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
