# Generated by Django 4.0.3 on 2023-05-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_conference_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='weather',
        ),
    ]
